@LOCALHOST = http://localhost:5078


# Exemplo de criação de estudante
POST {{LOCALHOST}}/api/v1/student/create
Accept: application/json
Content-Type: application/json

{
  "firstName": "Diogo",
  "lastName": "Nascimento",
  "dateOfBirth": "1990-05-03T03:30:25.184Z",
  "email": "diogonascii@gmail.com",
  "phoneNumber": "21985043074",
  "address": "Rua Fábio Luz",
  "city": "Rio de Janeiro",
  "state": "Rio de Janeiro",
  "postalCode": "20720350"
}

###
