# This is a generated file. Not intended for manual editing.
services:
  prof.hub.webapi:
    build:
      context: "D:\\@diogonasci\\repos\\prof-hub"
      dockerfile: "src/Prof.Hub.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "profhubwebapi:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\diogo\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\@diogonasci\\repos\\prof-hub\\src\\Prof.Hub.WebApi:/app:rw"
    - "D:\\@diogonasci\\repos\\prof-hub:/src:rw"
    - "C:\\Users\\diogo\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "D:\\Rider\\JetBrains Rider 2024.2.7\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\diogo\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_26_23_57_36:/var/opt/rider-debugger:rw"
    working_dir: "/app"
