# This is a generated file. Not intended for manual editing.
services:
  prof.hub.webapi:
    build:
      context: "D:\\@diogonasci\\repos\\prof-hub"
      dockerfile: "src/Prof.Hub.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Prof.Hub.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "profhubwebapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\diogo\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\@diogonasci\\repos\\prof-hub\\src\\Prof.Hub.WebApi:/app:rw"
    - "D:\\@diogonasci\\repos\\prof-hub:/src:rw"
    working_dir: "/app"
